language: python

python:
    - "3.6"
    - "nightly"

cache: pip

services:
    - redis-server
    - mongodb

jobs:
  include:
    - stage: test
      install:
        - pip install -q -U pip
        - pip install -q -r requirements.txt
        - pushd sbin
        - ./db_mgmt_json.py -p
        - ./db_mgmt_cpe_dictionary.py -p
        - popd
      script:
        - pytest --cov-report term --cov=./ test/ -v

notifications:
    email:
        on_success: change
        on_failure: change

after_success:
    - codecov