language: python

cache: pip

jobs:
  include:
    - stage: web tests
      if: type = pull_request
      python: 3.6
      script: pytest test/web/ -v
      services:
          - docker
      before_install:
          - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          - sudo apt-get update
          - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
      install:
          - git clone https://github.com/cve-search/CVE-Search-Docker.git
          - pushd CVE-Search-Docker
          - pip install requests
          - pip install beautifulsoup4
          - pip install pytest
          - docker-compose build --build-arg REPO=$TRAVIS_PULL_REQUEST_SLUG --build-arg BRANCH=$TRAVIS_PULL_REQUEST_BRANCH
          - docker-compose up -d
          - sleep 240
          - popd
    - stage: web tests
      if: type = push
      python: 3.6
      script: pytest test/web/ -v
      services:
        - docker
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
      install:
        - git clone https://github.com/cve-search/CVE-Search-Docker.git
        - pushd CVE-Search-Docker
        - pip install requests
        - pip install beautifulsoup4
        - pip install pytest
        - docker-compose build
        - docker-compose up -d
        - sleep 240
        - popd

notifications:
    email:
        on_success: change
        on_failure: change
