language: python

python:
    - "3.6"
    - "nightly"

cache: pip

services:
    - redis-server
    - mongodb

install:
    - pip install -q -U pip
    - pip install -q -r requirements.txt
    - pushd sbin
    - ./db_mgmt_json.py -p
    # Avoid creating a log > 4mb and making travis unhappy.
    - ./db_mgmt_cpe_dictionary.py | cat &
    - PID=$!
    - while sleep 60; do kill -0 $PID && echo 'Still running' || break; done
    - popd
    #- pushd web
    #- python minimal-web.py &
    #- popd

script:
    - pytest --cov-report term --cov=./ test/ -v

notifications:
    email:
        on_success: change
        on_failure: change

after_success:
    - codecov