language: python

cache: pip

jobs:
  include:
    - stage: unit tests
      python: 3.6
      script: pytest --cov-report term --cov=./ test/ -v
      services:
          - redis-server
          - mongodb
      install:
          - pip install -q -U pip
          - pip install -q -r requirements.txt
          - pushd sbin
          - ./db_mgmt_json.py -p
          - ./db_mgmt_cpe_dictionary.py -p
          - popd
    - stage: unit tests
      python: nightly
      script: pytest --cov-report term --cov=./ test/ -v
      services:
          - redis-server
          - mongodb
      install:
          - pip install -q -U pip
          - pip install -q -r requirements.txt
          - pushd sbin
          - ./db_mgmt_json.py -p
          - ./db_mgmt_cpe_dictionary.py -p
          - popd

notifications:
    email:
        on_success: change
        on_failure: change

after_success:
    - codecov