name: Build and Deploy documentation
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Cache pip
        id: cache-dev-pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          # path: ~/.cache/pip
          path: ${{ env.pythonLocation}}
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}_${{ env.pythonLocation}}_pip_dev_v1_3.6_${{ hashFiles('requirements-dev.txt') }}
      - name: Install dependencies
        if: steps.cache-dev-pip.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Build Documentation
        run: |
          cd docs
          make clean
          make html
      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
          CLEAN: true