name: Build and Deploy documentation
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build Documentation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          cd docs
          make clean
          make html
      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
          CLEAN: true
